pipeline {
    agent any
    
    stages {
        stage('Clean Up') {
            steps {
                script {
                    // Stop and remove any running containers with the name "backend"
                    sh '''
                    if [ "$(docker ps -q -f name=backend)" ]; then
                        docker stop backend
                        docker rm backend
                    fi
                    '''
                    sh '''
                    if [ "$(docker images -q backend)" ]; then
                        docker rmi -f backend
                    fi
                    '''
                }
            }
        }
        
        stage('Build Image') {
            steps {
                script {
                    // Build the Docker image
                    sh 'docker build -t backend ./backend'
                }
            }
        }
        
        stage('Run Container') {
            steps {
                script {
                    // Run the Docker container
                    sh 'docker run -d --name backend -p 4000:4000 backend'
                }
            }
        }
    }
}
